(function(g){var window=this;'use strict';var Lxb=function(a,b){g.W.call(this,{I:"button",La:["ytp-miniplayer-expand-watch-page-button","ytp-button","ytp-miniplayer-button-top-left"],W:{title:"{{title}}","data-tooltip-target-id":"ytp-miniplayer-expand-watch-page-button","aria-keyshortcuts":"i","data-title-no-tooltip":"{{data-title-no-tooltip}}"},V:[{I:"svg",W:{height:"24px",version:"1.1",viewBox:"0 0 24 24",width:"24px"},V:[{I:"g",W:{fill:"none","fill-rule":"evenodd",stroke:"none","stroke-width":"1"},V:[{I:"g",W:{transform:"translate(12.000000, 12.000000) scale(-1, 1) translate(-12.000000, -12.000000) "},
V:[{I:"path",W:{d:"M19,19 L5,19 L5,5 L12,5 L12,3 L5,3 C3.89,3 3,3.9 3,5 L3,19 C3,20.1 3.89,21 5,21 L19,21 C20.1,21 21,20.1 21,19 L21,12 L19,12 L19,19 Z M14,3 L14,5 L17.59,5 L7.76,14.83 L9.17,16.24 L19,6.41 L19,10 L21,10 L21,3 L14,3 Z",fill:"#fff","fill-rule":"nonzero"}}]}]}]}]});this.J=a;this.listen("click",this.onClick,this);this.updateValue("title",g.yT(a,"Expand","i"));this.update({"data-title-no-tooltip":"Expand"});this.addOnDisposeCallback(g.wT(b.Te(),this.element))},Mxb=function(a){g.W.call(this,
{I:"div",
S:"ytp-miniplayer-ui"});this.G=!1;this.player=a;this.T(a,"minimized",this.nh);this.T(a,"onStateChange",this.zea)},Nxb=function(a){g.fV.call(this,a);
this.B=new g.MJ(this);this.j=new Mxb(this.player);this.j.hide();g.GT(this.player,this.j.element,4);a.isMinimized()&&(this.load(),g.Nv(a.getRootNode(),"ytp-player-minimized",!0))};
g.x(Lxb,g.W);Lxb.prototype.onClick=function(){this.J.jb("onExpandMiniplayer")};g.x(Mxb,g.W);g.k=Mxb.prototype;
g.k.show=function(){this.j=new g.Bv(this.g5,null,this);this.j.start();if(!this.G){this.tooltip=new g.qX(this.player,this);g.M(this,this.tooltip);g.GT(this.player,this.tooltip.element,4);this.tooltip.scale=.6;this.le=new g.SV(this.player);g.M(this,this.le);this.B=new g.W({I:"div",S:"ytp-miniplayer-scrim"});g.M(this,this.B);this.B.Ka(this.element);this.T(this.B.element,"click",this.m0);var a=new g.W({I:"button",La:["ytp-miniplayer-close-button","ytp-button"],W:{"aria-label":"Close"},V:[g.UE()]});g.M(this,
a);a.Ka(this.B.element);this.T(a.element,"click",this.SU);a=new Lxb(this.player,this);g.M(this,a);a.Ka(this.B.element);this.C=new g.W({I:"div",S:"ytp-miniplayer-controls"});g.M(this,this.C);this.C.Ka(this.B.element);this.T(this.C.element,"click",this.m0);var b=new g.W({I:"div",S:"ytp-miniplayer-button-container"});g.M(this,b);b.Ka(this.C.element);a=new g.W({I:"div",S:"ytp-miniplayer-play-button-container"});g.M(this,a);a.Ka(this.C.element);var c=new g.W({I:"div",S:"ytp-miniplayer-button-container"});
g.M(this,c);c.Ka(this.C.element);this.N=new g.CW(this.player,this,!1);g.M(this,this.N);this.N.Ka(b.element);b=new g.BW(this.player,this);g.M(this,b);b.Ka(a.element);this.nextButton=new g.CW(this.player,this,!0);g.M(this,this.nextButton);this.nextButton.Ka(c.element);this.K=new g.jX(this.player,this);g.M(this,this.K);this.K.Ka(this.B.element);this.progressBar=new g.HW(this.player,this);g.M(this,this.progressBar);g.GT(this.player,this.progressBar.element,4);this.D=new g.W({I:"div",S:"ytp-miniplayer-buttons"});
g.M(this,this.D);g.GT(this.player,this.D.element,4);a=new g.W({I:"button",La:["ytp-miniplayer-close-button","ytp-button"],W:{"aria-label":"Close"},V:[g.UE()]});g.M(this,a);a.Ka(this.D.element);this.T(a.element,"click",this.SU);a=new g.W({I:"button",La:["ytp-miniplayer-replay-button","ytp-button"],W:{"aria-label":"Close"},V:[g.xya()]});g.M(this,a);a.Ka(this.D.element);this.T(a.element,"click",this.Xba);this.T(this.player,"presentingplayerstatechange",this.i5);this.T(this.player,"appresize",this.kc);
this.T(this.player,"fullscreentoggled",this.kc);this.kc();this.G=!0}this.player.getPlayerState()!==0&&g.W.prototype.show.call(this);this.progressBar.show();this.player.unloadModule("annotations_module")};
g.k.hide=function(){this.j&&(this.j.dispose(),this.j=void 0);g.W.prototype.hide.call(this);this.player.isMinimized()||(this.G&&this.progressBar.hide(),this.player.loadModule("annotations_module"))};
g.k.ya=function(){this.j&&(this.j.dispose(),this.j=void 0);g.W.prototype.ya.call(this)};
g.k.SU=function(){this.player.stopVideo();this.player.jb("onCloseMiniplayer")};
g.k.Xba=function(){this.player.playVideo()};
g.k.m0=function(a){if(a.target===this.B.element||a.target===this.C.element)this.player.getPlayerStateObject().isOrWillBePlaying()?this.player.pauseVideo():this.player.playVideo()};
g.k.nh=function(){g.Nv(this.player.getRootNode(),"ytp-player-minimized",this.player.isMinimized())};
g.k.Cg=function(){this.progressBar.Tc();this.K.Tc()};
g.k.g5=function(){this.Cg();this.j&&this.j.start()};
g.k.i5=function(a){g.xF(a.state,32)&&this.tooltip.hide()};
g.k.kc=function(){g.h4a(this.progressBar,0,this.player.qb().getPlayerSize().width,!1);g.IW(this.progressBar)};
g.k.zea=function(a){this.player.isMinimized()&&(a===0?this.hide():this.show())};
g.k.Te=function(){return this.tooltip};
g.k.Zx=function(a,b,c,d,e){var f=0,h=d=0,l=g.Qs(a);if(b){c=g.Iv(b,"ytp-prev-button")||g.Iv(b,"ytp-next-button");var m=g.Iv(b,"ytp-play-button"),n=g.Iv(b,"ytp-miniplayer-expand-watch-page-button");c?f=h=12:m?(b=g.Os(b,this.element),h=b.x,f=b.y-12):n&&(h=g.Iv(b,"ytp-miniplayer-button-top-left"),f=g.Os(b,this.element),b=g.Qs(b),h?(h=8,f=f.y+40):(h=f.x-l.width+b.width,f=f.y-20))}else h=c-l.width/2,d=25+(e||0);b=this.player.qb().getPlayerSize().width;e=f+(e||0);l=g.ze(h,0,b-l.width);e?(a.style.top=e+"px",
a.style.bottom=""):(a.style.top="",a.style.bottom=d+"px");a.style.left=l+"px"};g.x(Nxb,g.fV);g.k=Nxb.prototype;g.k.onVideoDataChange=function(){if(this.player.getVideoData()){var a=this.player.getVideoAspectRatio(),b=16/9;a=a>b+.1||a<b-.1;g.Nv(this.player.getRootNode(),"ytp-rounded-miniplayer-not-regular-wide-video",a)}};
g.k.create=function(){g.fV.prototype.create.call(this);this.B.T(this.player,"videodatachange",this.onVideoDataChange);this.onVideoDataChange()};
g.k.dn=function(){return!1};
g.k.load=function(){this.player.hideControls();this.j.show()};
g.k.unload=function(){this.player.showControls();this.j.hide()};g.eV("miniplayer",Nxb);})(_yt_player);
